### ISSUE TITLE
New JS Include

### ISSUE THREAD

**Issue by AlanBCole** [CuBoulder/pantheon-upstream-express-production#29]
We need to make a new include for the  chat bot many sites will be using going forward. Some example code to follow below.

**Comment by jcsparks** [comment]
[SalesForce Chat Client.txt](https://github.com/CuBoulder/pantheon-upstream-express-production/files/12196569/SalesForce.Chat.Client.txt)
Here's the main code with the auto open attachment.

**Comment by jcsparks** [comment]
This portion does the auto-open : 

    if(!(/Android|webOS|iPhone|iPad|iPod|mobile.+firefox|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent))){
                    
        embedded_svc.addEventHandler("onSettingsCallCompleted", function(data) {
            console.log("onSettingsCallCompleted event was fired. Agent availability status is " + data.isAgentAvailable ? "online": "offline");
            setTimeout(function() { 
            	embedded_svc.bootstrapEmbeddedService();
            }, 15000);    
        });
     }

**Comment by AlanBCole** [comment]
Closing this issue as the related pr is now merged in.
